// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.petclinic.customersserver.tars.customers;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface OwnerResourceServant {

	public Owner createOwner(Owner owner);

	public Owner findOwner(int ownerId);

	public java.util.List<Owner> findAll();

	public void updateOwner(int ownerId, Owner ownerRequest);
}
