// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.petclinic.customersserver.tars.customers;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PetResourceServant {

	public java.util.List<PetType> getPetTypes();

	public Pet processCreationForm(PetRequest petRequest, int ownerId);

	public void processUpdateForm(PetRequest petRequest);

	public PetDetails findPet(int petId);
}
