// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.petclinic.customersserver.tars.customers;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PetRequest {

	@TarsStructProperty(order = 0, isRequire = false)
	public int id = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String birthDate = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String name = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public int typeId = 0;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTypeId() {
		return typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public PetRequest() {
	}

	public PetRequest(int id, String birthDate, String name, int typeId) {
		this.id = id;
		this.birthDate = birthDate;
		this.name = name;
		this.typeId = typeId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(birthDate);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(typeId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PetRequest)) {
			return false;
		}
		PetRequest other = (PetRequest) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(birthDate, other.birthDate) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(typeId, other.typeId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(id, 0);
		if (null != birthDate) {
			_os.write(birthDate, 1);
		}
		if (null != name) {
			_os.write(name, 2);
		}
		_os.write(typeId, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.read(id, 0, false);
		this.birthDate = _is.readString(1, false);
		this.name = _is.readString(2, false);
		this.typeId = _is.read(typeId, 3, false);
	}

}
