// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.customers;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class OwnerResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_createOwner(Owner ret);

	public abstract void callback_findOwner(Owner ret);

	public abstract void callback_findAll(java.util.List<Owner> ret);

	public abstract void callback_updateOwner();

}
