// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.customers;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PetResourcePrx {

	public java.util.List<PetType> getPetTypes();

	public java.util.List<PetType> getPetTypes(@TarsContext java.util.Map<String, String> ctx);

	public void async_getPetTypes(@TarsCallback PetResourcePrxCallback callback);

	public void async_getPetTypes(@TarsCallback PetResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public Pet processCreationForm(PetRequest petRequest, int ownerId);

	public Pet processCreationForm(PetRequest petRequest, int ownerId, @TarsContext java.util.Map<String, String> ctx);

	public void async_processCreationForm(@TarsCallback PetResourcePrxCallback callback, PetRequest petRequest, int ownerId);

	public void async_processCreationForm(@TarsCallback PetResourcePrxCallback callback, PetRequest petRequest, int ownerId, @TarsContext java.util.Map<String, String> ctx);

	public void processUpdateForm(PetRequest petRequest);

	public void processUpdateForm(PetRequest petRequest, @TarsContext java.util.Map<String, String> ctx);

	public void async_processUpdateForm(@TarsCallback PetResourcePrxCallback callback, PetRequest petRequest);

	public void async_processUpdateForm(@TarsCallback PetResourcePrxCallback callback, PetRequest petRequest, @TarsContext java.util.Map<String, String> ctx);

	public PetDetails findPet(int petId);

	public PetDetails findPet(int petId, @TarsContext java.util.Map<String, String> ctx);

	public void async_findPet(@TarsCallback PetResourcePrxCallback callback, int petId);

	public void async_findPet(@TarsCallback PetResourcePrxCallback callback, int petId, @TarsContext java.util.Map<String, String> ctx);
}
