// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.customers;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class PetResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_getPetTypes(java.util.List<PetType> ret);

	public abstract void callback_processCreationForm(Pet ret);

	public abstract void callback_processUpdateForm();

	public abstract void callback_findPet(PetDetails ret);

}
