// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.petclinic.vetsserver.tars.vets;

import com.qq.tars.protocol.annotation.*;

@Servant
public interface VetResourceServant {

	public java.util.List<Vet> showResourcesVetList();
}
