// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.petclinic.visitsserver.tars.visits;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface VisitResourceServant {

	public Visit create(Visit visit, int petId);

	public java.util.List<Visit> visits(int petId);

	public Visits visitsMultiGet(java.util.List<java.lang.Integer> petIds);
}
