server:
  #端口号
  port: 8083

spring:
  profiles:
    active: production
  cache:
    cache-names: customers
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
#    schema: classpath*:db/mysql/schema.sql
#    data: classpath*:db/mysql/data.sql
#    url: jdbc:mysql://localhost:3306/tars?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: ALWAYS

vets:
  cache:
    ttl: 10
    heap-size: 10