spring:
  profiles:
    active: production
  cache:
    cache-names: customers
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
    url: jdbc:hsqldb:mem:test
    username: sa
    password:

vets:
  cache:
    ttl: 10
    heap-size: 10