spring:
  profiles:
    active: production
  cache:
    cache-names: customers
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql

vets:
  cache:
    ttl: 10
    heap-size: 10