// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.visits;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class VisitResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_create(Visit ret);

	public abstract void callback_visits(java.util.List<Visit> ret);

	public abstract void callback_visitsMultiGet(Visits ret);

}
