// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.vets;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface VetResourcePrx {

	public java.util.List<Vet> showResourcesVetList();

	public java.util.List<Vet> showResourcesVetList(@TarsContext java.util.Map<String, String> ctx);

	public void async_showResourcesVetList(@TarsCallback VetResourcePrxCallback callback);

	public void async_showResourcesVetList(@TarsCallback VetResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
