// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.mytars.client.tars.vets;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class VetResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_showResourcesVetList(java.util.List<Vet> ret);

}
